### ISSUE TITLE
Has anyone started a Denver Police Department scraper? 

### ISSUE THREAD

**Issue by faithlierheimer** [Police-Data-Accessibility-Project/Scrapers#31]
Would like to start experimenting with that if not.

**Comment by OscarVanL** [comment]
Hi Faith,

As far as I know the answer is no, so please go ahead!

The resource [here](https://docs.google.com/spreadsheets/d/1nD4LnjU1b1b9RgQNcn6op-Oj3ZQVcgz-2bUgEU5RVXA) is to document links to various state/county court portals, those highlighted in green have been completed to some extent. Please add any links for Denver if you come across any. If you start work on any scraper, you should also consult [here](https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/blob/master/README.md) and [here](https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/blob/master/CONTRIBUTING.md) when you're getting started on your scraper.

You'll notice that, for many states, counties, and municipalities, we have very little information mapped out.  That's currently where we're headed, in addition to getting an MVP out.

Please heavily document anything you work on, as it will, at some point, need to be integrated with PDAP's backend system at some point.  Some of the current slowness in developing scrapers right now is somewhat due to the future logistical issues of integrating different scrapers without a scraping model in place first, as well as us waiting on nonprofit status paperwork.

If you're not in our slack group yet, the _announcements channel should be useful for getting up to date with the project, and scrapers_general should be helpful if you have any more questions :)

**Comment by faithlierheimer** [comment]
Gotcha, thank you very much! I will definitely document heavily. It'll take some time to get started on it but I just wanted to check.
